name: CI Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Install build dependencies
        run: pip install -r build/requirements-dev.txt

      - name: Make staging directory for build
        run: mkdir stage

      - run: python -m png

      - name: Package tools for Linux
        run: cp -r tools/linux stage/tools

      - name: Package build
        run: |
          cd build/linux
          sh build.sh
          cd ../..
          cp -r bin/pymapconv/* stage

      - uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: stage/
