name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare Output Directory
        run: mkdir -p bin

      - name: Package Tools for Windows
        run: cp -r tools/win bin/tools

      -

      - uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: dist/win
