name: CI Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make staging directory for build
        run: mkdir stage

      - name: Package tools for Windows
        run: cp -r tools/windows stage/tools

      - name: Install build dependencies
        run: |
          cd build
          pip install -r ./requirements-dev.txt

        - name: Package build
          run: |
            cd build/win
            ./build.bat
            cd ../..
            cp -r bin/pymapconv/* stage

      - uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: stage/
